name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
      # - name: Create a Release
      #   uses: elgohr/Github-Release-Action@v5
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     title: Release ${{ github.ref }}
      #     tag: ${{ github.ref }}
        
      - name: Build NuGet package
        run: |
          $version = "${{ github.ref }}".TrimStart('refs/tags/v')
          Get-ChildItem -Path src -Filter *.csproj -Recurse | 
          ForEach-Object { dotnet pack $_.FullName --configuration Release --no-build --output ./nuget -p:Version=$version }
        shell: pwsh
      
      - name: Push NuGet package
        run: dotnet nuget push "./nuget/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate --exclude-symbols